[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "py_xaquatic_runner"
version = "0.1.0"
description = "Runner and IO utilities for XAQUATIC models"
authors = [{ name = "Mike Devin Fuchs" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.0",
    "pandas>=2.0",
    "pydantic-xml>=2.0",
    "lxml>=4.9",
    "h5py>=3.0"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["py_xaquatic_runner"]
